version: "3.9"

services:
  dinky:
    image: "dinkydocker/dinky-standalone-server:${DINKY_VERSION}-flink${FLINK_VERSION}"
    ports:
      - "8888:8888"
    env_file: .env
    networks:
      - dinky
    volumes:
      - ${CUSTOM_JAR_PATH}:/opt/dinky/customJar/

  jobmanager:
    image: flink:${FLINK_VERSION}-scala_2.12-java8
    ports:
      - "8081:8081"
    command: jobmanager
    env_file: .env
    volumes:
      - ${CUSTOM_JAR_PATH}:/opt/flink/lib/customJar/
    networks:
      - dinky

  taskmanager:
    image: flink:${FLINK_VERSION}-scala_2.12-java8
    command: taskmanager
    env_file: .env
    volumes:
      - ${CUSTOM_JAR_PATH}:/opt/flink/lib/customJar/
    networks:
      - dinky

  mysql:
    image: mysql:8.0
    container_name: dinky_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - D:\env\mysql\config\my-80.cnf:/etc/mysql/my.cnf
      - mysql_data_8:/var/lib/mysql
    networks:
      - dinky
    ports:
      - "3306:3306"
      - "33060:33060"

volumes:
  mysql_data_8:  # 定义数据卷
    driver: local

networks:
  dinky:
    driver: bridge  # 可以指定网络驱动类型，默认为 bridge